# Generated by Django 2.0.3 on 2020-02-13 14:25

import ckeditor_uploader.fields
from django.db import migrations
import read_statistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200208_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name=read_statistics.models.ReadDetail),
        ),
    ]
